name: deploy on github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy on Github Pages
    runs-on: ubuntu-latest
    env:
      CONTENTFUL_HOST: cdn.contentful.com
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      GOOGLE_ANALYTICS_GTAG: ${{ secrets.GOOGLE_ANALYTICS_GTAG }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"

      - name: Install packages
        run: |
          npm i -g gatsby-cli@3.0.0 yarn@1.22.10
          yarn install

      - name: Build
        run: "gatsby build"

      - name: Deploy on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          external_reposityory: Furafrafrfr/Furafrafrfr.github.io
          publish_dir: ./public
