name: deploy on github pages

on:
  push:
    branches:
      - main
      - test-actions
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy on Github Pages
    runs-on: ubuntu-latest
    env:
      GOOGLE_ANALYTICS_GTAG: ${{ secrets.GOOGLE_ANALYTICS_GTAG }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        working-directory: ./blog-front
        run: |
          yarn global add gatsby-cli
          yarn install --frozen-lockfile

      - name: Build
        working-directory: ./blog-front
        run: 'gatsby build'

      - name: Deploy on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          external_repository: Furafrafrfr/Furafrafrfr.github.io
          publish_branch: main
          publish_dir: ./blog-front/public
